# schema
# <new_table_name>:
#   <first_table>:
#     <column>: [include only changed columns]
#       [use only parameters which changes]
#       action: <new_action> [default: copy] (valid: copy, add, remove)
#       name: <new_column_name> [id - not necessary] (name == id ? action = remove)
#       from: <new_table_name> [take values from this table using mapping from 'from' table
#                                i.e. you have x2 table and you want to port ids from it but
#                                mapped as those ids from x1 table (one-to-one relation)
#                                only for ids!]
#       field: <new_table_field> [if mapping is not by id, but by other field, put here its name]
#     <column2>:
#       <...>
#     <...>
#   <second_table>:
#     <...>
#   <...>
01_users:
  users:
    pass:
      name: password
    time:
      name: created_on
    timeact:
      name: updated_at
    priv:
      name: privileges
    s_hydview:
      action: remove
    www:
      name: www_page
    wwwdesc:
      name: www_description
    sunuml:
      action: remove
    surname:
      name: lastname
    privileges:
      action: remove
02_cathedrals:
  cathedrals:
03_users_students:
  users_k1:
    id:
      from: users
      name: user_id
    band:
      name: sgroup
    indeks:
      name: sindex
    gg:
      name: gadu_gadu
    module:
      name: speciality_id
    modified:
      action: remove
    nband:
      action: remove
04_users_lecturers:
  users_k2:
    id:
      from: users
      name: user_id
    cathedral:
      from: cathedrals
      name: cathedral_id
    consul:
      name: consultations
05_subjects:
  specs:
    name:
      name: head
    acronim:
      name: acronym
    type:
      action: remove
    season:
      action: remove
06_news_types:
  news_types:
07_news:
  news:
    alogin:
      from: users
      field: login
      name: user_id
    aname:
      action: remove
    nyear:
      name: for_year
    piece:
      name: body
    mreads:
      name: times_readed
    spec:
      action: remove
    thread:
      action: remove
    type:
      action: remove
    year:
      action: remove
08_uploaded_files:
  files:
    filename1:
      action: remove
    name:
      name: head
    time:
      name: date
    alogin:
      action: remove
    aid:
      from: users
      name: user_id
    down:
      name: downloads
    spec:
      from: subjects
      name: subject_id
    rlogin:
      action: remove
    rid:
      action: remove
    sectype:
      action: remove
    secgroup:
      action: remove
