# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "users", :force => true do |t|
    t.column "login",           :string,    :limit => 50,                     :null => false
    t.column "password",        :string,    :limit => 40,                     :null => false
    t.column "email",           :string,    :limit => 50,                     :null => false
    t.column "registered",      :timestamp,                                   :null => false
    t.column "last_activity",   :timestamp,                                   :null => false
    t.column "firstname",       :string,    :limit => 50
    t.column "lastname",        :string,    :limit => 50
    t.column "privileges",      :integer,                                     :null => false
    t.column "question",        :text
    t.column "answer",          :text
    t.column "www_page",        :string,    :limit => 200
    t.column "www_description", :text
    t.column "voted",           :boolean,                  :default => false, :null => false
    t.column "signature",       :text
    t.column "last_ip",         :string,    :limit => 15
    t.column "activated",       :boolean,                  :default => false, :null => false
    t.column "kind",            :string,    :limit => 0,                      :null => false
  end

  create_table "users_lecturers", :force => true do |t|
    t.column "users_id",      :integer,               :null => false
    t.column "place",         :string,  :limit => 30
    t.column "title",         :string,  :limit => 50
    t.column "cathedral",     :integer, :limit => 4
    t.column "consultations", :string,  :limit => 50
    t.column "phone",         :string,  :limit => 15
    t.column "photo",         :string,  :limit => 50
  end

  add_index "users_lecturers", ["users_id"], :name => "users_id"

  create_table "users_students", :force => true do |t|
    t.column "users_id",  :integer,               :null => false
    t.column "group",     :string,  :limit => 4,  :null => false
    t.column "module",    :integer, :limit => 4,  :null => false
    t.column "new_group", :string,  :limit => 6,  :null => false
    t.column "index",     :integer, :limit => 6,  :null => false
    t.column "gadu_gadu", :integer, :limit => 15
    t.column "icq",       :integer, :limit => 15
    t.column "cell",      :string,  :limit => 15
  end

  add_index "users_students", ["users_id"], :name => "users_id"

  add_foreign_key "users_lecturers", ["users_id"], "users", ["id"], :name => "users_lecturers_ibfk_1"

  add_foreign_key "users_students", ["users_id"], "users", ["id"], :name => "users_students_ibfk_1"

end
