# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "cathedrals", :force => true do |t|
    t.column "name", :string, :limit => 20
  end

  create_table "group_ufiles", :force => true do |t|
    t.column "group_id", :integer, :null => false
    t.column "ufile_id", :integer, :null => false
  end

  add_index "group_ufiles", ["group_id"], :name => "group_id"
  add_index "group_ufiles", ["ufile_id"], :name => "ufile_id"

  create_table "groups", :force => true do |t|
    t.column "code", :string, :limit => 80
    t.column "head", :string,               :null => false
    t.column "body", :text
  end

  create_table "groups_news", :force => true do |t|
    t.column "new_id",   :integer, :null => false
    t.column "group_id", :integer, :null => false
  end

  add_index "groups_news", ["new_id"], :name => "new_id"
  add_index "groups_news", ["group_id"], :name => "group_id"

  create_table "groups_users", :force => true do |t|
    t.column "user_id",  :integer, :null => false
    t.column "group_id", :integer, :null => false
  end

  add_index "groups_users", ["user_id"], :name => "user_id"
  add_index "groups_users", ["group_id"], :name => "group_id"

  create_table "news", :force => true do |t|
    t.column "head",         :string,                                 :null => false
    t.column "body",         :text,                                   :null => false
    t.column "ip",           :string,    :limit => 15
    t.column "date",         :timestamp,                              :null => false
    t.column "times_readed", :integer,                 :default => 0, :null => false
    t.column "for_year",     :integer,                                :null => false
  end

  create_table "news_types", :force => true do |t|
    t.column "name", :string, :limit => 20, :null => false
  end

  create_table "news_users", :force => true do |t|
    t.column "new_id",  :integer, :null => false
    t.column "user_id", :integer, :null => false
  end

  add_index "news_users", ["new_id"], :name => "new_id"
  add_index "news_users", ["user_id"], :name => "user_id"

  create_table "statistics", :force => true do |t|
    t.column "ip",              :string,    :limit => 15
    t.column "browser_name",    :string,    :limit => 100
    t.column "browser_version", :string,    :limit => 50
    t.column "os_name",         :string,    :limit => 100
    t.column "os_version",      :string,    :limit => 50
    t.column "resolution",      :string,    :limit => 10
    t.column "color_depth",     :string,    :limit => 2
    t.column "date",            :timestamp,                :null => false
  end

  create_table "subject_users", :force => true do |t|
    t.column "user_id",    :integer, :null => false
    t.column "subject_id", :integer, :null => false
  end

  add_index "subject_users", ["user_id"], :name => "user_id"
  add_index "subject_users", ["subject_id"], :name => "subject_id"

  create_table "subjects", :force => true do |t|
    t.column "user_id", :integer, :null => false
    t.column "head",    :string,  :null => false
    t.column "body",    :text
  end

  add_index "subjects", ["user_id"], :name => "user_id"

  create_table "subjects_ufiles", :force => true do |t|
    t.column "subject_id", :integer, :null => false
    t.column "ufile_id",   :integer, :null => false
  end

  add_index "subjects_ufiles", ["subject_id"], :name => "subject_id"
  add_index "subjects_ufiles", ["ufile_id"], :name => "ufile_id"

  create_table "ufiles", :force => true do |t|
    t.column "filename", :string,                 :null => false
    t.column "head",     :string,                 :null => false
    t.column "body",     :text
    t.column "date",     :timestamp,              :null => false
    t.column "kind",     :string,    :limit => 0, :null => false
  end

  create_table "ufiles_users", :force => true do |t|
    t.column "user_id",  :integer, :null => false
    t.column "ufile_id", :integer, :null => false
  end

  add_index "ufiles_users", ["user_id"], :name => "user_id"
  add_index "ufiles_users", ["ufile_id"], :name => "ufile_id"

  create_table "users", :force => true do |t|
    t.column "login",           :string,    :limit => 50,                     :null => false
    t.column "password",        :string,    :limit => 40,                     :null => false
    t.column "email",           :string,    :limit => 50,                     :null => false
    t.column "registered",      :timestamp,                                   :null => false
    t.column "last_activity",   :timestamp,                                   :null => false
    t.column "firstname",       :string,    :limit => 50
    t.column "lastname",        :string,    :limit => 50
    t.column "privileges",      :integer,                                     :null => false
    t.column "question",        :text
    t.column "answer",          :text
    t.column "www_page",        :string,    :limit => 200
    t.column "www_description", :text
    t.column "voted",           :boolean,                  :default => false, :null => false
    t.column "signature",       :text
    t.column "last_ip",         :string,    :limit => 15
    t.column "activated",       :boolean,                  :default => false, :null => false
    t.column "kind",            :string,    :limit => 0,                      :null => false
  end

  create_table "users_lecturers", :force => true do |t|
    t.column "user_id",       :integer,               :null => false
    t.column "cathedral_id",  :integer,               :null => false
    t.column "place",         :string,  :limit => 30
    t.column "title",         :string,  :limit => 50
    t.column "cathedral",     :integer, :limit => 4
    t.column "consultations", :string,  :limit => 50
    t.column "phone",         :string,  :limit => 15
    t.column "photo",         :string,  :limit => 50
  end

  add_index "users_lecturers", ["user_id"], :name => "user_id"
  add_index "users_lecturers", ["cathedral_id"], :name => "cathedral_id"

  create_table "users_students", :force => true do |t|
    t.column "user_id",   :integer,               :null => false
    t.column "group",     :string,  :limit => 4,  :null => false
    t.column "module",    :integer, :limit => 4,  :null => false
    t.column "new_group", :string,  :limit => 6,  :null => false
    t.column "index",     :integer, :limit => 6,  :null => false
    t.column "gadu_gadu", :integer, :limit => 15
    t.column "icq",       :integer, :limit => 15
    t.column "cell",      :string,  :limit => 15
  end

  add_index "users_students", ["user_id"], :name => "user_id"

  add_foreign_key "group_ufiles", ["group_id"], "groups", ["id"], :name => "group_ufiles_ibfk_1"
  add_foreign_key "group_ufiles", ["ufile_id"], "ufiles", ["id"], :name => "group_ufiles_ibfk_2"

  add_foreign_key "groups_news", ["new_id"], "news", ["id"], :name => "groups_news_ibfk_1"
  add_foreign_key "groups_news", ["group_id"], "groups", ["id"], :name => "groups_news_ibfk_2"

  add_foreign_key "groups_users", ["user_id"], "users", ["id"], :name => "groups_users_ibfk_1"
  add_foreign_key "groups_users", ["group_id"], "groups", ["id"], :name => "groups_users_ibfk_2"

  add_foreign_key "news_users", ["new_id"], "news", ["id"], :name => "news_users_ibfk_1"
  add_foreign_key "news_users", ["user_id"], "users", ["id"], :name => "news_users_ibfk_2"

  add_foreign_key "subject_users", ["user_id"], "users", ["id"], :name => "subject_users_ibfk_1"
  add_foreign_key "subject_users", ["subject_id"], "subjects", ["id"], :name => "subject_users_ibfk_2"

  add_foreign_key "subjects", ["user_id"], "users", ["id"], :name => "subjects_ibfk_1"

  add_foreign_key "subjects_ufiles", ["subject_id"], "subjects", ["id"], :name => "subjects_ufiles_ibfk_1"
  add_foreign_key "subjects_ufiles", ["ufile_id"], "ufiles", ["id"], :name => "subjects_ufiles_ibfk_2"

  add_foreign_key "ufiles_users", ["user_id"], "users", ["id"], :name => "ufiles_users_ibfk_1"
  add_foreign_key "ufiles_users", ["ufile_id"], "ufiles", ["id"], :name => "ufiles_users_ibfk_2"

  add_foreign_key "users_lecturers", ["user_id"], "users", ["id"], :name => "users_lecturers_ibfk_1"
  add_foreign_key "users_lecturers", ["cathedral_id"], "cathedrals", ["id"], :name => "users_lecturers_ibfk_2"

  add_foreign_key "users_students", ["user_id"], "users", ["id"], :name => "users_students_ibfk_1"

end
